# Generated by Django 5.2 on 2025-05-20 01:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('verification_code_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
