# Generated by Django 5.2 on 2025-05-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('floor', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
