# Generated by Django 5.2 on 2025-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
